import { describe, expect, it } from "vitest";
import { validateTraceArchive } from "@/lib/trace-archive";

// Playwright 1.62 trace generated by context.tracing for a page create/setContent/click flow.
const PLAYWRIGHT_TRACE_BASE64 =
  "UEsDBBQACAgIACtWBV0AAAAAAAAAAAAAAAALAAAAdHJhY2UudHJhY2Wtlk9v3DYQxe/5FOr04BaQVeo/JbiG2yYFDBRBDmkudQ8UOdplwyUFktqNYex3L6hd2SvXabpobgIJ/d68N7OjfYAtWieNhpbG4O8HhBa40R4/+UszeGm0gxiMlSupoQUlO8vsPcTQWbNzaN+yzfTK2pqNHDcQw6DY/c7K1dp/mNGQJlWWkEumhjW7TGuaV1lekpIQEuBHmfYBtHmNPRuV/yBxNxjroe2ZchiDQ4XcG/tGr6RGB+0ff8bAOMfBvzY7rQwTDtrjCcSwfQQ8wE4Kv4Y2zSiJYY2hNGjrjOz3U7W+N3YDLQhmd1JDDDum1HsZfKU1LRuS1lVeF0UMG6ONN1ryw21JsqSqaQxOfPyN6dXIViGLv9iWOW7lVIdH52/FT95b2Y0ej3EJ5tlluJIC4jnvWwHtHOvl8ewGK5rnVc8yRgjnJKVdljUZIw1jeVEJAvtXD3PfOuyNxQBkSk208HBTQQzOM+vnqvOkqpsYuGIuZPbzQfKXgyLEsEG/NuF1jbt3wVMMA7NsE1q0P9HDLerJ48StKEmaovov3OEZdDq4nW9uatYUaSo62hcpbzJOUk57knHsupRSkcNpEaz3aF/0jFq8f6qsKWOw6EblZ0Fo4SrYu17wPhMiXYZY0SwhtHgy+6sNnT3x6NBPzqeEnpyu/UYF4W+E4UExCgfXV93ovdGRFD9e2FFfXNtRR94yjlc/HK6ujzmb0UObE0JImFPpf9deBmD4AUCY5zOTfDKuzOpF1/7RcFHnwaBzh/Acei/1KuqD9YgfzMZRqCocj6Gy6G6q7A7giy2ji5Y1JCmq7Mt9ScmzxjQkoXX6L43hSvKPi57MuwVa+NaO+h9Jf/VYp6KPuTZpQvPsNNc5wN7YSBnOvLHfXYTCLr4/C0yTZlpaj+BoxkUWnVFbFJE30cns3YEd9R28NH3nCDdJUS4mhXmPm2EyNaUfMR5W/pnQsqyXbk6DQoUb1D4Y6jDaSic7hXGEmnUKRcS0iJwPz2eI1mmTZPlSc9aR7quKlEsVx61RKniT2psofMwi2UcaUaA4E15Xz+DCaHxSOKVJPYz+Zd5gpJ425ydoiyzJY7iHNqVJuT+jmixNmupZoAPa8P39H7NRFzRpqmyJPWVNjs8F1vnnh83xNYoxtFyzrVyx6f9LGL1eaunWZ0k1SUaqpdQpdM22eMQuO//yEp3Qj1t0opfp/tXfUEsHCPGtppWIAwAA5wkAAFBLAwQUAAgICAArVgVdAAAAAAAAAAAAAAAADQAAAHRyYWNlLm5ldHdvcmsDAFBLBwgAAAAAAgAAAAAAAABQSwMEFAAACAgAK1YFXfu9jW1pAAAAfgAAAAwAAAB0cmFjZS5zdGFja3M9y8EKwjAMANB/yTmu7ZBRPe7kP4QcQsmgm5OtzYYg/rs40OuD94Ih37XClcAtJe9i6mxeXJLHLvU05KdtRZtzd1t7c6momDbzWIERqkmavpU6JPIYsY0IwMxI8ZALhvYnwR8U/N/4/QFQSwECPwMUAAgICAArVgVd8a2mlYgDAADnCQAACwAJAAAAAAAAAAAApIEAAAAAdHJhY2UudHJhY2VVVAUAA8OycmpQSwECPwMUAAgICAArVgVdAAAAAAIAAAAAAAAADQAJAAAAAAAAAAAApIHBAwAAdHJhY2UubmV0d29ya1VUBQADw7JyalBLAQI/AxQAAAgIACtWBV37vY1taQAAAH4AAAAMAAkAAAAAAAAAAAC0gf4DAAB0cmFjZS5zdGFja3NVVAUAA8OycmpQSwUGAAAAAAMAAwDJAAAAkQQAAAAA";

function little16(value: number): number[] {
  return [value & 0xff, (value >>> 8) & 0xff];
}

function little32(value: number): number[] {
  return [value & 0xff, (value >>> 8) & 0xff, (value >>> 16) & 0xff, (value >>> 24) & 0xff];
}

function zip(entryNames: string[], encrypted = false): Uint8Array {
  const encoder = new TextEncoder();
  const localParts: number[][] = [];
  const centralParts: number[][] = [];
  let localOffset = 0;
  const flags = encrypted ? 1 : 0;

  for (const entryName of entryNames) {
    const name = [...encoder.encode(entryName)];
    const local = [
      ...little32(0x04034b50),
      ...little16(20),
      ...little16(flags),
      ...little16(0),
      ...little16(0),
      ...little16(0),
      ...little32(0),
      ...little32(0),
      ...little32(0),
      ...little16(name.length),
      ...little16(0),
      ...name,
    ];
    localParts.push(local);
    centralParts.push([
      ...little32(0x02014b50),
      ...little16(20),
      ...little16(20),
      ...little16(flags),
      ...little16(0),
      ...little16(0),
      ...little16(0),
      ...little32(0),
      ...little32(0),
      ...little32(0),
      ...little16(name.length),
      ...little16(0),
      ...little16(0),
      ...little16(0),
      ...little16(0),
      ...little32(0),
      ...little32(localOffset),
      ...name,
    ]);
    localOffset += local.length;
  }

  const central = centralParts.flat();
  const eocd = [
    ...little32(0x06054b50),
    ...little16(0),
    ...little16(0),
    ...little16(entryNames.length),
    ...little16(entryNames.length),
    ...little32(central.length),
    ...little32(localOffset),
    ...little16(0),
  ];
  return Uint8Array.from([...localParts.flat(), ...central, ...eocd]);
}

describe("validateTraceArchive", () => {
  it("accepts a real Playwright trace ZIP", () => {
    const archive = new Uint8Array(Buffer.from(PLAYWRIGHT_TRACE_BASE64, "base64"));
    expect(validateTraceArchive(archive, archive.length)).toBeNull();
  });

  it("accepts multi-context trace entry names", () => {
    const archive = zip(["0-trace.trace", "0-trace.network"]);
    expect(validateTraceArchive(archive, archive.length)).toBeNull();
  });

  it("rejects an arbitrary ZIP", () => {
    const archive = zip(["notes.txt"]);
    expect(validateTraceArchive(archive, archive.length)).toMatch(/not a recognized/);
  });

  it("rejects empty and garbage buffers", () => {
    expect(validateTraceArchive(new Uint8Array(), 0)).toMatch(/not a recognized/);
    expect(validateTraceArchive(Uint8Array.from([1, 2, 3]), 3)).toMatch(/not a recognized/);
  });

  it("rejects encrypted entries", () => {
    const archive = zip(["trace.trace", "trace.network"], true);
    expect(validateTraceArchive(archive, archive.length)).toMatch(/not a recognized/);
  });

  it.each([
    ["entry counts", (data: DataView, eocd: number) => {
      data.setUint16(eocd + 8, 0xffff, true);
      data.setUint16(eocd + 10, 0xffff, true);
    }],
    ["directory size", (data: DataView, eocd: number) => {
      data.setUint32(eocd + 12, 0xffffffff, true);
    }],
    ["directory offset", (data: DataView, eocd: number) => {
      data.setUint32(eocd + 16, 0xffffffff, true);
    }],
  ])("rejects Zip64 %s sentinels", (_label, mutate) => {
    const archive = zip(["trace.trace", "trace.network"]);
    mutate(new DataView(archive.buffer), archive.length - 22);
    expect(validateTraceArchive(archive, archive.length)).toMatch(/not a recognized/);
  });

  it("rejects when the fetched tail does not contain the EOCD", () => {
    const archive = zip(["trace.trace", "trace.network"]);
    const incompleteTail = archive.subarray(0, archive.length - 22);
    expect(validateTraceArchive(incompleteTail, archive.length)).toMatch(/not a recognized/);
  });

  it("rejects when the central directory is outside the fetched tail", () => {
    const archive = zip(["trace.trace", "trace.network"]);
    const eocdOnly = archive.subarray(archive.length - 22);
    expect(validateTraceArchive(eocdOnly, archive.length)).toMatch(/not a recognized/);
  });
});
